### ISSUE TITLE
Bimbingan 3 Februari 2015

### ISSUE THREAD

**Issue by pascalalfadian** [tearvan/SkripsiKIRIDataMining#4]
Next:
- UI bisa pilih ID3 / C4.5
- Bisa menghitung jumlah klasifikasi benar (dalam %)
- Bisa memparsing tree hasil `buildClassifier()` menjadi struktur sendiri atau format [dot](http://www.graphviz.org/content/dot-language)

**Comment by tearvan** [comment]
sudah diimplementasikan di d01c213
