### ISSUE TITLE
Bimbingan 10 Februari 2015

### ISSUE THREAD

**Issue by pascalalfadian** [tearvan/SkripsiKIRIDataMining#5]
Mohon dibuat jadi 2 percobaan:
- Percobaan 1:
  - sama seperti sekarang, tetapi hanya memasukkan day-of-week dan hour (tanggal + menit dibuang)
  - kelasnya, dibuat: -1 untuk masuk bandung, 0 untuk tetap, +1 untuk keluar
- Percobaan 2:
  - Dihitung frekuensi per day-of-week, jam.
  - hitung maximum frekuensi per day-of-week,jam, kemudian kelasnya dibagi 5:
    - sangat sedikit: 0-20% dari maksimum
    - sedikit: 20-40% dari maksimum
    - sedang: 40-60% dari maksimum
    - banyak: 60-80% dari maksimum
    - sangat banyak: 80-100% dari maksimum

Kalau sudah, langsung saja draft dokumen.

**Comment by tearvan** [comment]
percobaan pertama sudah dilakukan di https://github.com/tearvan/SkripsiKIRIDataMining/commit/d01c213ba07f8edc21bb62b8aab3ce37e28c216b
